### ISSUE TITLE
conda installation support

### ISSUE THREAD

**Issue by laoshaw** [root-project/cling#197]
can I install cling via conda?

I'm comparing cling vs xeus-cling and the latter has conda installation which is really convenient.

Thanks,

**Comment by gouarin** [comment]
cling is available on conda for linux because we need it for xeus-cling.
The current version is 0.3 but since few days, I'm working on the conda
packaging for cling 0.5 and xeus-cling for windows, linux and mac osx.

So I hope in few days or weeks you will have all you need ;).

2017-11-29 20:13 GMT+01:00 laoshaw <notifications@github.com>:

**Comment by laoshaw** [comment]
Thanks. what's the relationship between cling and xeus-cling? I just tried xeus-cling in an existing miniconda3 and it failed to start:

https://github.com/QuantStack/xeus-cling/issues/76

**Comment by gouarin** [comment]
The idea of xeus-cling is to use

- xeus which implements the messaging protocol of Jupyter in C++.
- cling as an interpreter for the C++ kernel like IPython does for the
Python kernel.

I will take a look at your issue.

2017-11-29 20:25 GMT+01:00 laoshaw <notifications@github.com>:

**Comment by Axel-Naumann** [comment]
To this looks like it's answered. Thanks!
