### ISSUE TITLE
CLing install taking too much resources on EC2 instance

### ISSUE THREAD

**Issue by alphadevuser** [root-project/cling#288]
I am trying to install cling on an EC2 instance that has 4 GB ram and 15 GB hard disk. When I build cling(as mentioned in `README.md`), it takes more than 13 GB of hard disk ! And the process ends complaining about insufficient space.
Am I doing something wrong ? Or is the build process supposed to take this much hard disk space ?

**Comment by nwoeanhinnogaehr** [comment]
I think the disk usage is normal given that the project is quite large, but I'm not sure what's going on with the RAM usage right now. I was able to compile everything fine a few months ago within 16GB of RAM but when I tried yesterday it died due to OOM. Going to add some swap space and try again...

**Comment by nwoeanhinnogaehr** [comment]
Okay, tried with a 16GB swap and that wasn't enough. There's obviously a pretty severe memory leak somewhere.

**Comment by Jimut123** [comment]
I tried it in KDE Plasma in manjaro, it enables baloo file extractor and takes up all system resources.

**Comment by Axel-Naumann** [comment]
@nwoeanhinnogaehr @alphadevuser please confirm that the `CMAKE_BUILD_TYPE` did not have debug symbols, as suggested by @oshadura ? That changes *everything*.
