### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by reikdas** [root-project/cling#302]
Compiler - GCC 9.1.0

Using the given instructions - 
```
wget https://raw.githubusercontent.com/root-project/cling/master/tools/packaging/cpt.py
chmod +x cpt.py
./cpt.py --create-dev-env Debug --with-workdir=./cling-build/
```
(Did not run --check-requirements, because I am using Arch Linux which is not supported by cpt's --check-requirements)
Build fails with the error - 
```
make[2]: *** [tools/lli/CMakeFiles/lli.dir/build.make:63: tools/lli/CMakeFiles/lli.dir/lli.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:35070: tools/lli/CMakeFiles/lli.dir/all] Error 2
```

I wasn't able to find the exact place where lli causes the Error(the lines immediately preceding the above lines did not seem relevant) to occur for more information so I have attached the entire build log (it is an extremely big text file) in case it helps - 
[cling_log.txt](https://github.com/root-project/cling/files/3577089/cling_log.txt)
as well as the CMakeError.log from the builddir - 
[CMakeError.log](https://github.com/root-project/cling/files/3577285/CMakeError.log)

**Comment by QuLogic** [comment]
Search for `error:`:
```
/home/reik/cling-build/cling-src/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h:722:26: error: could not convert ‘((llvm::orc::remote::OrcRemoteTargetClient<ChannelT>*)this)->callB<llvm::orc::remote::OrcRemoteTargetRPCAPI::ReadMem>(Src, Size)’ from ‘Expected<vector<unsigned char,allocator<unsigned char>>>’ to ‘Expected<vector<char,allocator<char>>>’
```
which looks like #297.

**Comment by Axel-Naumann** [comment]
Could you do me a big favor and check whether http://root.cern.ch/gitweb?p=cling.git;a=commitdiff;h=2c92b57062e22c14c015c7bd3f9c7d9d3197defa fixes this?

**Comment by reikdas** [comment]
I am still having some build problems with cpt but I think they are unrelated to this particular issue. 
Thanks!

**Comment by dpellegr** [comment]
Hi, I encountered this issue again today in my clean build.

The error (admittedly quite buried in a bunch of useless output) is a mismatched type parameter in the return type of the function:
`Expected<std::vector<char>> readMem(char *Dst, JITTargetAddress Src, uint64_t Size)`
declared and defined at line 716 of:
`llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h`

It has been fixed in more recent version of llvm: https://github.com/llvm/llvm-project/blob/45251ef5345b3c81c8f394d42d252de039c72566/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h#L642

Note how the vector template parameter is now `unit8_t` or `unsigned char`.
I applied the same change in my `/src` and I was able to complete the compilation, producing all the `LLVM*.cmake` files which I was missing.

**Comment by Axel-Naumann** [comment]
> I guess this adds a bit of pressure on #276 :)

Not really, because cling builds just fine, unless you enable unrelated llvm targets.

**Comment by dpellegr** [comment]
> unless you enable unrelated llvm targets.
Which AFAIK are needed if you want to use cling as library AKA compile cling/tools/demo/

**Comment by Axel-Naumann** [comment]
Hmm that'd mean we need to tweak its `CMakeLists.txt`! Thanks for that clarification; I wasn't aware / forgot.
