### ISSUE TITLE
Question: what is the correct url used by CPT for retrieving the cling-patches tar.gz ?  

### ISSUE THREAD

**Issue by stephane-rolland** [root-project/cling#356]
I feel a bit intrigued, maybe I'm doing things awkwardly. 

(A bit of context : I'm working on the packaging of Cling for NixOS system. As this system does not follow the traditionnal FHS, and uses its own philosophy and its own functional programming language, I cannot use rely on cpt.py for building things. Consequently I will try to mimic what cpt.py does.)

In the code of Cling Packaging Tool , [file cpt.py - function fetch_llvm - line 196](https://github.com/root-project/cling/blob/master/tools/packaging/cpt.py#L196-L197), it downloads a tar.gz file from the url:

    wget(url='https://github.com/%s/%s' % (user, repo.replace('.git', '')) + '/archive/cling-patches-r%s.tar.gz' % llvm_revision, out_dir=workdir)  

But on the linux command line I get a 404 error when I try:

    wget -O - https://github.com/root-project/cling/archive/cling-patches-rrelease_50.tar.gz | tar xz

I use llvm_revision = release_50 as it is what is return by: 

    https://raw.githubusercontent.com/root-project/cling/master/LastKnownGoodLLVMSVNRevision.txt

So my question is, what is the correct url so as to fetch the patches ?

A subsidiary question : do you know how to get the list of tar.gz exposed by cling on github?

The only way I found for the moment is using: https://api.github.com/repos/root-project/cling/releases ; I have to recheck, but I don't think it lists the archive/cling-patches-r%s.tar.gz stuffs.

**Comment by reikdas** [comment]
Some information that might help you - 

We don't need to use patched LLVM anymore. Please feel free to use the latest LLVM 5 release that you are able to. 

But we do need to use the root-project patched version of Clang (at least for now). So I'll answer your question from that perspective since cpt has a similar code block for `fetch_clang` - https://github.com/root-project/cling/blob/master/tools/packaging/cpt.py#L319. The line that you are having issues with - 
> wget(url='https://github.com/%s/%s' % (user, repo.replace('.git', '')) + '/archive/cling-patches-r%s.tar.gz' % llvm_revision, out_dir=workdir)  

is only encountered if you use the `--with-clang-url=<https://github.com/....>` flag. 

If you can use git to get the patched version of clang, the next paragraph is relevant - 
Just do not use the `with-clang-url` flag, and get the patched clang from http://root.cern.ch/git/clang.git (this is where cpt sets it as the default - https://github.com/root-project/cling/blob/master/tools/packaging/cpt.py#L1885 in case you are interested) and checkout the cling-patches-rrelease_50 branch.

If you cannot use git, it might be an issue. Maybe someone with better knowledge could say if we store a tarball of the patched clang somewhere.

**Comment by stephane-rolland** [comment]
Great. With your indication I can build clang and cling much better. Everything performs well until almost the end :-)
I still have an issue, but I'm not sure yet what's causing it, I'm gathering information to identify what's wrong.

The NixOs build system is complaining about the produced executable $out/bin/cling ($out is where we put produces files from compilation and so on). indeed it tells me it is not an executable... Don't want to add too much details for the moment in case it is not related (highly likely), I'm still gathering info.

I'll update here to confirm my assumption everything is ok with the clang sources when selecting the branch ling-patches-rrelease_50 branch from  http://root.cern.ch/git/clang.git

**Comment by stephane-rolland** [comment]
Now at first sight, I have the same exact error as @SylvainCorlay in the issue he opened recently, related to:

 undefined reference to `clang::RewriteBuffer::write(llvm::raw_ostream&) const'

**Comment by stephane-rolland** [comment]
Just as a side-note, about the usage of fetch_llvm, I have not dug into the details at all, and I have not the background on the history of this tool which is several years old. However it was referenced more than once in the code.
I was probably mislead by these multiple references.

> $ rg fetch_llvm
> cpt.py
> 188:def fetch_llvm(llvm_revision):
> 2261:        fetch_llvm(llvm_revision)
> 2386:        fetch_llvm(llvm_revision)
> 2477:        fetch_llvm(llvm_revision)
> 2506:    fetch_llvm(llvm_revision)
> 2524:    fetch_llvm(llvm_revision)
> 2542:    fetch_llvm(llvm_revision)
> 2560:    fetch_llvm(llvm_revision)
> 2576:    fetch_llvm(llvm_revision)
>

**Comment by SylvainCorlay** [comment]
Thanks @stephane-rolland. Yes I think the patch in question should be included in cling.

**Comment by reikdas** [comment]
Closing since it looks like the original query was answered.
