### ISSUE TITLE
Cannot use `gCling->allowRedefinition()` in script

### ISSUE THREAD

**Issue by hzhangxyz** [root-project/cling#371]
Hello, I am using cling 0.7, I can use allow redefinition feature in REPL but in script, it does not work

`cat init.C` get
```
#include "cling/Interpreter/Interpreter.h"
gCling->allowRedefinition()
```

`cling --version` get
```
0.7
```

`cling < init.C` run correctly and get
```
****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
```

However
```
cling

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ .L init.C
In file included from input_line_3:1:
/home/hzhangxyz/Downloads/init.C:2:1: error: unknown type name 'gCling'
gCling->allowRedefinition()
^
/home/hzhangxyz/Downloads/init.C:2:7: error: cannot use arrow operator on a type
gCling->allowRedefinition()
      ^
[cling]$
```

If I run `cling init.C` directly, I get similar error
```
 ~/Downloads  cling init.C
In file included from input_line_3:1:
/home/hzhangxyz/Downloads/init.C:2:1: error: unknown type name 'gCling'
gCling->allowRedefinition()
^
/home/hzhangxyz/Downloads/init.C:2:7: error: cannot use arrow operator on a type
gCling->allowRedefinition()
      ^
```

**Comment by jalopezg-r00t** [comment]
Hello @hzhangxyz,

This is the intended behavior for cling.  In the first case (stdin redirect), input is handled as if it were typed by the user at the prompt; this means that we can apply some transformations, e.g. wrap statements.

On the contrary, the other two cases that you provide are equivalent and the source code is parsed as-is.  In this case, input is expected to be legal C++ code, i.e. you need to wrap stataments into a function.  Additionally, if you use `.x` instead of `.L`, cling will invoke a function that has the same name as the file, removing the suffix (`init` in your original text).

That said, commit 904796d2bbf9dc08413dd188ff618a34d55d8d31, changes the way you turn or/off this feature, e.g.
```
gClingOpts->AllowRedefinition = 1;  // or 0
```

Cheers,
J.
