### ISSUE TITLE
Update to most recent Clang version for C++17 and 20 support?

### ISSUE THREAD

**Issue by pdeitel** [root-project/cling#421]
Are there any plans to update the version of clang used? Would love to have C++20  support in an interactive environment.

**Comment by SimeonEhrig** [comment]
Yes, it is planed. At the moment, @vgvassilev [planning](https://compiler-research.org/assets/presentations/CaaS_03_06_2021.pdf) the port to LLVM 13. Unfortunately this upgrade will take some time, because we need to replace the old OrcJITv1 API with the OrcJITv2 API, which is a big change and needs a lot of verification.

By the way, the Cling developers are working hard to get as many of the Cling-specific Clang patches into the Clang/LLVM upstream as possible to speed up future upgrades to new LLVM versions. You can see the progress in the slides from the monthly [compiler research meeting](https://compiler-research.org/meetings/).

**Comment by pdeitel** [comment]
Any updates on this?

**Comment by SimeonEhrig** [comment]
Yes, there is a PR https://github.com/root-project/root/pull/10294.

**Comment by vgvassilev** [comment]
I think so. Let's close it.
