### ISSUE TITLE
building from source fails on debian 11

### ISSUE THREAD

**Issue by BretG137** [root-project/cling#445]
- [ ] Checked for duplicates

### Describe the bug
  Using the instructions:
wget https://raw.githubusercontent.com/root-project/cling/master/tools/packaging/cpt.py
chmod +x cpt.py
./cpt.py --check-requirements && ./cpt.py --create-dev-env Debug --with-workdir=./cling-build/
fails

### Expected behavior
it works

### To Reproduce
 wget https://raw.githubusercontent.com/root-project/cling/master/tools/packaging/cpt.py
chmod +x cpt.py
./cpt.py --check-requirements && ./cpt.py --create-dev-env Debug --with-workdir=./cling-build/

### Setup
 newest, debian 11, wget https://raw.githubusercontent.com/root-project/cling/master/tools/packaging/cpt.py

### Additional context
 Terminal output is attached
[terminaloutput.txt](https://github.com/root-project/cling/files/7653337/terminaloutput.txt)

**Comment by Axel-Naumann** [comment]
```
/home/user/cling-build/cling-src/tools/clang/lib/Parse/ParseInit.cpp:550:1: internal compiler error: Segmentation fault
  550 | }
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
```
says that your compiler crashed. I suspect that this is fixed in a later GCC - I have never seen this, but we don't build with debian 11.

Your GCC crashes compiling `clang/lib/Parse/ParseObjc.cpp` which isn't ours but clang's.

There's not much we can do, I'm afraid. Try with a different GCC; if all fails see whether you can successfully compiler clang-9. If not, consider reporting to them, please!
