### ISSUE TITLE
Maintenance of cling

### ISSUE THREAD

**Issue by naweiss** [root-project/cling#492]
Is this repo still maintained?
On the one hand there is no new release since 2021.
On the other hand there are multiple commits from 2022 and 2023.

**Comment by dimitry-ishenko** [comment]
@Freed-Wu if you are on Ubuntu 22.04 or 20.04, you can find native Debian packages for cling and xeus-cling here:

https://launchpad.net/~ppa-verse/+archive/ubuntu/xeus-cling

**Comment by iMichka** [comment]
A new release would be good though.
We are trying to rebuild `cling` in homebrew and are hitting some issues: https://github.com/Homebrew/homebrew-core/pull/131473#issuecomment-1555916463

I did not have to investigate if a commit fixed this, but having a new release would at least simplify the investigation for us (we only build from stable releases).

**Comment by Axel-Naumann** [comment]
Hey folks - we are maintaining it (it's used in production for [really](https://atlas.cern/) [big](https://cms.cern/) [thi](https://alice.cern/)[ngs](https://lhcb-outreach.web.cern.ch/) and we will maintain it probably for the next 20 years!

But the effort we put into community maintenance isn't satisfying at the moment. I do hope that CERN will give us a new FTE starting next year to take care of cling (and the cling-base Python bindings)!

That said: a release is in the plans, I believe; @vgvassilev do you have an ETA? I think we still have several test failures since the upgrade to llvm13?

**Comment by vgvassilev** [comment]
@jalopezg-git, I believe these tests failures were resolved. Is that correct?

**Comment by Axel-Naumann** [comment]
No need to believe, you can just check yourself: https://lcgapp-services.cern.ch/root-jenkins/view/cling/job/cling-generic-build/

**Comment by dimitry-ishenko** [comment]
> upgrade to llvm13?

This is so last year... 😞 If you want to target C++20, even LLVM/Clang 15 is no good (no support for ranges).

**Comment by Axel-Naumann** [comment]
😂 llvm15 is on the radar! Hopefully for this year?

**Comment by Axel-Naumann** [comment]
@hahnjo FYI re ranges

**Comment by dimitry-ishenko** [comment]
Unfortunately, they've really screwed a pooch with Clang. You'd think this simple c++20 example should compile with Clang, right?

```c++
#include <iostream>
#include <ranges>
namespace views = std::ranges::views;

int main()
{
    for (auto n : views::iota(0, 20) | views::drop(5) | views::take(10))
        std::cout << n << ' ';
    std::cout << std::endl;
    return 0;
}
```
Not unless you are using Clang 16: https://godbolt.org/z/6jjhb7Pr8

**Comment by jalopezg-git** [comment]
> @jalopezg-git, I believe these tests failures were resolved. Is that correct?

According to the report in the URL provided by @Axel-Naumann (https://lcgapp-services.cern.ch/root-jenkins/view/cling/job/cling-generic-build/), there seems to be still a couple of issues:
- [Cling/DynamicLibraryManager/cached_realpath_C](https://lcgapp-services.cern.ch/root-jenkins/view/cling/job/cling-generic-build/lastCompletedBuild/BUILDTYPE=Release,COMPILER=native,LABEL=ROOT-ubuntu2004/testReport/Cling/DynamicLibraryManager/cached_realpath_C/): this is tracked here https://github.com/llvm/llvm-project/issues/61289.
- On macOS, many tests are failing due to the error below and it might be hiding a real problem somewhere; I'd suggest to fix this in the CI before.
```
ld: library not found for -lSystem
```

**Comment by vgvassilev** [comment]
@jalopezg-git, the issue seems to be resolved by https://reviews.llvm.org/D144276. Maybe we should try backporting?

**Comment by hahnjo** [comment]
> @jalopezg-git, the issue seems to be resolved by https://reviews.llvm.org/D144276. Maybe we should try backporting?

This change is pretty big and also relies on `orc_runtime`, that probably causes more problems than it solves. AFAICT `cached_realpath.C` is more of a unit test, I'm not sure how much value it provides. Maybe we can disable it if we detect that kind of problem?
