### ISSUE TITLE
please add jupyter kernel for c++20

### ISSUE THREAD

**Issue by blackgolfer** [root-project/cling#524]

**Comment by girdevstack** [comment]
Hey @ferdymercury  - do you happen to know what the release/update cycle for cling or who else could be pinged to cut a release? I see that the commit wit those changes were merged into main about a month ago from root https://github.com/root-project/cling/commit/628a18e48ba38b60d6fe7502790f9856074adb09 

thank you

**Comment by vgvassilev** [comment]
I could make a release if requested.

**Comment by girdevstack** [comment]
Hi @vgvassilev thank you for your response and @ferdymercury for your help :pray:. 

It would be great if you could cut a release to get those new kernels ready for the jupyter xeus_cling to pull in. It looks like their build is pulling in their dependencies from conda forge and cling hasn't been updated for any of the post 0.9 versions either. If 1.2 could be cut to get these changes incorporated and if you or someone else could push the new build version artifacts over to conda forge that would be fantastic too so that 1.0, 1.1, and 1.2 would be available to anyone that would like to use it ^_^

Do either of you happen to know who would be a good person to ping for a review on a PR in https://github.com/jupyter-xeus/xeus-cling to get their build updated to get the new version from your update after it gets through the build pipeline?

**Comment by girdevstack** [comment]
Thank you for getting the new release cut @vgvassilev - is there someone else that handles the conda forge artifacts? I still only see `0.9` as the newest version over there. https://anaconda.org/conda-forge/cling/labels

**Comment by girdevstack** [comment]
Disregard someone else over in xeus-cling found where that is getting built - https://github.com/conda-forge/cling-feedstock/pull/59

Sorry for the extra ping and thanks again :+1:
